kafkaConfig:
  brokers:
    - 'localhost:36715'
pluginName: 'geoPlugin'
pluginManagerUrl: 'https://plugin_template_url'
priority: 1      
type: 'blocking'
dbipv4: 'IP2LOCATION-LITE-DB11.BIN'
dbipv6: 'IP2LOCATION-LITE-DB11.IPV6.BIN'
